name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Fix: don't pin WiX; ensure or upgrade if preinstalled
      - name: Ensure WiX Toolset v3
        shell: pwsh
        run: choco install wixtoolset -y || choco upgrade wixtoolset -y

      - name: Build CLI
        run: |
          cargo build --release
          ./target/release/screenpipe.exe --help

      - name: Install frontend deps
        working-directory: screenpipe-app-tauri
        run: |
          npm config set legacy-peer-deps true
          npm install


      - name: Build Tauri (Windows)
        working-directory: screenpipe-app-tauri
        run: npm run tauri build

      - name: Upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenpipe-windows-bundle
          path: |
            screenpipe-app-tauri/src-tauri/target/release/bundle/msi/*.msi
            screenpipe-app-tauri/src-tauri/target/release/bundle/exe/*.exe
